BookAppStore-master/Areas/Admin/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using BookAppStore.Areas.Admin.Repository;
using BookAppStore.Areas.Admin.Models;
using BookAppStore.Data;
using BookAppStore.Models;

namespace BookAppStore.Areas.Admin.Controllers
{
    [Area("admin"), Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly AdminBookRepository _adminBookRepository = null;

        public BookController(UserManager<ApplicationUser> userManager,
            AdminBookRepository adminBookRepository)
        {
            _userManager = userManager;
            _adminBookRepository = adminBookRepository;
        }

        [Route("admin/manage-books")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("admin/manage-books/edit")]
        public async Task<IActionResult> UpdateBook(int id)
        {
            // display user book data
            var book = await _adminBookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound($"Unable to load user book data");
            }

            var allBooksModel = new AllBooksModel()
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                Category = book.Category,
                TotalPage = book.TotalPage,
            };

            return View(allBooksModel);
        }

        [HttpPost("admin/manage-books/edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateBook(AllBooksModel allBooksModel)
        {
            // check validate and update book data
            if (ModelState.IsValid)
            {
                var result = await _adminBookRepository.UpdateBookAsync(allBooksModel);

                if (result > 0)
                {
                    ViewBag.IsSuccess = true;
                    return View(allBooksModel);
                }

            }

            ModelState.AddModelError("", "Something is wrong! Please try again");

            return View(allBooksModel);
        }

        #region API Call
            
            [HttpGet]
            public async Task<IActionResult> BooksList()
            {
                // load data without refreshing the page
                return Json(new { data = await _adminBookRepository.AllBooksAsync() });
            }

            [HttpDelete]
            [Route("admin/manage-books/delete")]
            public async Task<IActionResult> DeleteBook(AllBooksModel allBooksModel)
            {
                // delete book method
                var book = await _adminBookRepository.DeleteBookAsync(allBooksModel);
                if (book == null)
                {
                    return Json(new { success = false, message = "Error while deleting book" });
                }

                return Json(new { success = true, message = "book deleted successful!" });
            }

        #endregion
    }
}

BookAppStore-master/Areas/Admin/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using BookAppStore.Areas.Admin.Repository;
using BookAppStore.Areas.Admin.Models;
using BookAppStore.Models;

namespace BookAppStore.Areas.Admin.Controllers
{
    [Area("admin"), Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleRepository _roleRepository = null;
        public RoleController(RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager,
            RoleRepository roleRepository)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _roleRepository = roleRepository;
        }

        [Route("admin")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("admin/add-role")]
        public IActionResult AddRole()
        {
            // add new role form/page
            return View();
        }

        [HttpPost("admin/add-role")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(RoleModel roleModel)
        {
            // validate the form and add role
            if (ModelState.IsValid)
            {
                var result = await _roleRepository.AddRoleAsync(roleModel);
                if (result.Succeeded)
                {
                    ViewBag.IsSuccess = true;
                    ModelState.Clear();
                    return View();
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(roleModel);
        }

        [HttpGet("admin/update-role")]
        public async Task<IActionResult> UpdateRole(string id)
        {
            // retrieve role data
            var role = await _roleRepository.GetRoleById(id);

            var model = new RoleModel()
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }

        [HttpPost("admin/update-role")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateRole(RoleModel roleModel)
        {
            // update the fole
            if (ModelState.IsValid)
            {
                var result = await _roleRepository.UpdateRoleAsync(roleModel);

                if (result.Succeeded)
                {
                    ViewBag.IsSuccess = true;
                    return View(roleModel);
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(roleModel);
        }

        [Route("admin/manage-users")]
        public IActionResult AllUsersList()
        {
            return View();
        }

        [HttpGet("admin/manage-users/edit")]
        public async Task<IActionResult> EditUsers(string id)
        {
            // edit / update users
            var user = await _roleRepository.GetUserById(id);
            if (user == null)
            {
                return NotFound($"Unable to load user data");
            }

            var userRoles = await _userManager.GetRolesAsync(user);

            var model = new EditUserModel()
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                UserName = user.Email,
                Email = user.Email,
                Roles = userRoles
            };

            return View(model);
        }

        [HttpPost("admin/manage-users/edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUsers(EditUserModel editUserModel)
        {
            // validate and update user data
            if (ModelState.IsValid)
            {
                var result = await _roleRepository.EditUserAsync(editUserModel);

                if (result.Succeeded)
                {
                    ViewBag.IsSuccess = true;
                    return View(editUserModel);
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(editUserModel);
        }

        [HttpGet("admin/manage-users/edit/role")]
        public async Task<IActionResult> ManageUserRole(string userId)
        {
            // retrieve all roles with user selected role
            ViewBag.userId = userId;

            var user = await _roleRepository.GetUserById(userId);
            if (user == null)
            {
                return NotFound("Unable to load user data!");
            }

            var model = new List<ManageUsersRoleModel>();

            foreach (var role in _roleManager.Roles)
            {
                var manageUserRole = new ManageUsersRoleModel()
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    manageUserRole.IsSelected = true;
                }
                else
                {
                    manageUserRole.IsSelected = false;
                }

                model.Add(manageUserRole);
            }

            return View(model);
        }

        [HttpPost("admin/manage-users/edit/role")]
        public async Task<IActionResult> ManageUserRole(List<ManageUsersRoleModel> model, string userId)
        {
            // add / update user role
            var user = await _roleRepository.GetUserById(userId);
            if (user == null)
            {
                return NotFound("Unable to load user data!");
            }

            var role = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, role);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing role!");
                return View(model);
            }

            var result1 = await _userManager.AddToRolesAsync(user,
                model.Where(x => x.IsSelected).Select(y => y.RoleName));
            if (!result1.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected role to user");
                return View(model);
            }

            return RedirectToAction("EditUsers", new { Id = userId });
        }

        #region API Call
            [HttpGet]
            public async Task<IActionResult> RoleList()
            {
                // retrieve all roles
                return Json(new  { data = await _roleRepository.AllRolesAsync() });
            }

            [HttpGet]
            public async Task<IActionResult> UsersList()
            {
                // retrieve all users with their role
                return Json(new { data = await _roleRepository.AllUserAsync() });
            }

            [HttpDelete]
            [Route("admin/delete")]
            public async Task<IActionResult> DeleteRole(string id)
            {
                // delete role
                var deleteRole = await _roleRepository.DeleteRoleAsync(id);
                if (deleteRole == null)
                {
                    return Json(new { success = false, message = "Error while deleting role" });
                }

                return Json(new { success = true, message = "Delete successful" });
            }

            [HttpDelete]
            [Route("admin/manage-users/delete")]
            public async Task<IActionResult> DeleteAdminUser(string id)
            {
                // delete user
                var deleteUser = await _roleRepository.DeleteUserAsync(id);
                if (deleteUser == null)
                {
                    return Json(new { success = false, message = "Error while deleting user" });
                }

                return Json(new { success = true, message = "Delete user successful" });
            }
        #endregion
    }
}

BookAppStore-master/Controllers/BookController.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BookAppStore.Areas.Admin.Models;
using BookAppStore.Data;
using BookAppStore.Models;
using BookAppStore.Repository;
using BookAppStore.Service;

namespace BookAppStore.Controllers
{
    public class BookController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly BookRepository _bookRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserService _userService;
        private readonly BookStoreContext _context;

        public BookController(
            BookRepository bookRepository, 
            IWebHostEnvironment webHostEnvironment, UserService userService,
            UserManager<ApplicationUser> userManager, BookStoreContext context)
        {
            _bookRepository = bookRepository;
            _webHostEnvironment = webHostEnvironment; _userService = userService;
            _userManager = userManager; _context = context;
        }

        [Route("add-book")]
        public IActionResult AddBook()
        {
            return View();
        }

        [HttpPost("add-book")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddBook(BookModel bookModel)
        {
            // create new book
            if (ModelState.IsValid)
            {
                if (bookModel.CoverPhoto != null)
                {
                    string folder = "books/coverImg/";
                    bookModel.CoverImageUrl = await UploadImage(folder, bookModel.CoverPhoto);
                }

                if (bookModel.BookPdf != null)
                {
                    string folder = "books/pdfFile/";
                    bookModel.BookPdfUrl = await UploadImage(folder, bookModel.BookPdf);
                }

                int id = await _bookRepository.AddBookAsync(bookModel);
                if (id > 0)
                {
                    ViewBag.IsSuccess = true;
                    ModelState.Clear();
                    return View();
                }

            }

            ModelState.AddModelError("", "Something is wrong!");

            return View(bookModel);
        }

        [Route("book-detail")]
        public async Task<IActionResult> BookDetail(BookModel bookModel)
        {
            // display book detail with id

            var data = await  _bookRepository.GetBookByIdAsync(bookModel.Id);
            return View(data);
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }
    }
}

BookAppStore-master/Areas/Admin/Views/Book/Index.cshtml
@model AllBooksModel
@{
    ViewData["Title"] = "Manage Books - Administrator";
}

<div class="container">
    <div class="row p-o m-o">
        <div class="col-6">
            <h2 class="text-secondary">Books List</h2>
        </div>
        <div class="col-3 offset-3">
            <a asp-action="AddRole" asp-controller="Role" class="btn btn-info form-control text-white">
                Add New Book
            </a>
        </div>
        <div class="col-12 border p-3">

            @if (ViewBag.IsSuccess == true)
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    New book is added successfully. <br />
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }

            <table id="loadBooksData" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Book Name</th>
                        <th>Category</th>
                        <th>Author</th>
                        <th>Total Page</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

BookAppStore-master/Areas/Admin/Views/Book/UpdateBook.cshtml
@model AllBooksModel
@{
    ViewData["Title"] = "Update User Book - Administrator";
}

<div class="container">

    <hr />
    <div class="row">

        <div class="col-6 offset-3">
            <div class="content-section">
                <legend class="border-bottom mb-4">Update Book</legend>
                <br />
                @if (ViewBag.IsSuccess == true)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        Book is updated successfully. <br />
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                
                <form method="post" enctype="multipart/form-data" novalidate>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <input asp-for="Category" class="form-control" />
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TotalPage" class="control-label"></label>
                        <input asp-for="TotalPage" class="form-control" />
                        <span asp-validation-for="TotalPage" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col-5">
                            <input type="submit" value="Update Book" class="btn btn-outline-primary" />
                        </div>
                        <div class="col-5 col-offset-3">
                            <a asp-action="Index" asp-controller="Book" class="btn btn-outline-secondary">Go back</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial"></partial>
}